apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-depl
  labels:
    app: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci
  template:
    metadata:
      labels:
        app: ci
    spec:
      containers:
      - name: ci
        image: andwood/ci
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: ci-service
spec:
  selector:
    app: ci
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000